## Numpy Array Opetaions 

In [ ]:
import numpy as np


In [ ]:
arr = np.arange(15)
print("Original array : \n", arr)

print("Basic slicing :\n ", arr[5:10])
print("With step : \n", arr[5:10:2])

print("Reverse : \n", arr[::-1])


In [ ]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Secific element : \n", arr_2D[1, 1])
print("Entire row : \n", arr_2D[1, :])
print("Entire column : \n", arr_2D[:, 2])


Secific element : 
 5
Entire row : 
 [4 5 6]
Entire column : 
 [3 6 9]


### Sorting of Array

In [ ]:
# unsorted_array = np.random.randint(1,30,15)
unsorted_array = np.array([20, 25, 9, 21, 15, 16, 16, 14, 8, 22, 11, 8, 9, 3, 4])

print("Unsorted array : \n", unsorted_array)

sorted_array = np.sort(unsorted_array)

print("Sorted array : \n", sorted_array)


Unsorted array : 
 [20 25  9 21 15 16 16 14  8 22 11  8  9  3  4]
Sorted array : 
 [ 3  4  8  8  9  9 11 14 15 16 16 20 21 22 25]


### 2D array Sorting 

In [ ]:
array_2D_Unsorted = np.array([[1, 4, 3], [3, 5, 1], [8, 6, 2]])

print("Sort Array column wise : \n", np.sort(array_2D_Unsorted, axis=0))
print("Sort array Row Wise: \n", np.sort(array_2D_Unsorted, axis=1))


Sort Array column wise : 
 [[1 4 1]
 [3 5 2]
 [8 6 3]]
Sort array Row Wise: 
 [[1 3 4]
 [1 3 5]
 [2 6 8]]


### Filtering of Array

In [ ]:
# numbers = np.random.randint(1,25,15)
numbers = np.array([20, 25, 9, 21, 15, 16, 16, 14, 8, 22, 11, 8, 9, 3, 4])

even_numbers = numbers[numbers % 2 == 0]

print("Original array : \n", numbers)

print("Even number array : \n", even_numbers)


Original array : 
 [20 25  9 21 15 16 16 14  8 22 11  8  9  3  4]
Even number array : 
 [20 16 16 14  8 22  8  4]


### Filter With Mask

In [ ]:
mask_greater_than_5 = numbers > 5
mask_greater_than_10 = numbers > 10

print("numbers greater than 5 : \n", numbers[mask_greater_than_5])
print("numbers greater than 10 : \n", numbers[mask_greater_than_10])


numbers greater than 5 : 
 [20 25  9 21 15 16 16 14  8 22 11  8  9]
numbers greater than 10 : 
 [20 25 21 15 16 16 14 22 11]


### Fancy Indexing VS np.where()

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indics = [0, 4, 7]
print("Number of indices [0, 4, 7] : \n", numbers[indics])


Where_Result = np.where(numbers > 5)
print("Where Result : \n", numbers[Where_Result])


Number of indices [0, 4, 7] : 
 [1 5 8]
Where Result : 
 [ 6  7  8  9 10]


In [ ]:
Conditional_array = np.where(numbers > 5, numbers, "Not>5")
print("Conditional Array : \n", Conditional_array)


Conditional Array : 
 ['Not>5' 'Not>5' 'Not>5' 'Not>5' 'Not>5' '6' '7' '8' '9' '10']


### Adding and Removing Data

In [ ]:
array_1 = np.array(
    [
        1,
        2,
        3,
        4,
        5,
    ]
)
array_2 = np.array([6, 7, 8, 9, 10])

combined = np.concatenate((array_1, array_2))
print("Combined array : \n", combined)


Combined array : 
 [ 1  2  3  4  5  6  7  8  9 10]


### Array Compatibility Check

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])


if arr1.shape == arr2.shape == arr3.shape:
    combined = np.stack((arr1, arr2, arr3))
    print("Combined array : \n", combined)
else:
    print("All arrays should have same shape", arr1.shape, arr2.shape, arr3.shape)


Combined array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Adding new columns and rows 

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original array : \n", original_array)

new_row = np.array([10, 11, 12])
new_array = np.vstack((original_array, new_row))
print("new array with new row : \n", new_array)

new_col = np.array([[13], [14], [15]])
new_array = np.hstack((original_array, new_col))
print("new array with new col : \n", new_array)


Original array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
new array with new row : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
new array with new col : 
 [[ 1  2  3 13]
 [ 4  5  6 14]
 [ 7  8  9 15]]


### Delete element from an array 

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Original array : \n", arr)

deleted = np.delete(arr, 3)
print("Deleted array : \n", deleted)

deleted = np.delete(arr, [1, 4, 7])
print("Deleted array : \n", deleted)

deleted = np.delete(arr, np.s_[2:5])
print("Deleted array : \n", deleted)


Original array : 
 [ 1  2  3  4  5  6  7  8  9 10]
Deleted array : 
 [ 1  2  3  5  6  7  8  9 10]
Deleted array : 
 [ 1  3  4  6  7  9 10]
Deleted array : 
 [ 1  2  6  7  8  9 10]
